Feat: expose hook extend locales
nuxt-modules/i18n pull request #1319
Opened 2021-10-14 12:49 UTC by existe-deja

The purpose of this feature is to open to other modules the ability to add extra translated content and merge it to the main i18n messages.
Closes https://github.com/nuxt-community/i18n-module/issues/1308

2021-10-17 19:49 UTC, rchl requested changes
This should also be documented.

Maybe through an additional page in guides named `Extending locales hook` or something.

And if we really want to extend default options with `additionalMessages` (which I'm not sure about) then it should also be added to https://i18n.nuxtjs.org/options-reference.

2021-10-17 19:49 UTC, rchl commented on test/module.test.js
> +describe.only('Extend Locale with additionalMessages', () => {
Remove `.only`

2021-10-17 19:49 UTC, rchl commented on types/index.d.ts
> +  additionalMessages?: Array<LocaleMessages>
Do we really want to allow this to be provided through module options? I thought only through the hook.

On the other hand, I suppose it shouldn't be an issue but I think I'm not a big fan since it would be an third way to provide messages through module config and it can make things more confusing.

(Also, I prefer the `foo[]` syntax for arrays)

2021-10-17 19:49 UTC, rchl commented on test/fixture/extend-locales/pages/index.vue
> +    <div id="debug">{{ $i18n.messages }}</div>
Feel free to remove this once you don't need it.

2021-10-17 19:49 UTC, rchl commented on test/fixture/extend-locales/modules/externalModule/index.js
> +import lang from './lang'
Maybe avoid extra files and just include locales in this file. I don't think extra files add anything to testing.

2021-10-17 19:49 UTC, rchl commented on src/templates/plugin.utils.js
> +  })
The type annotation is redundant here.

Also I prefer `for of` loop since that avoids extra function calls and looks cleaner.

2021-10-17 19:49 UTC, rchl commented on test/fixture/extend-locales/modules/externalModule/index.js
> +export default function () {
```suggestion
/** @type {import('@nuxt/types').Module} */
export default function () {
```

2021-10-17 19:49 UTC, rchl commented on src/templates/plugin.main.js
> +            mergeAdditionalMessages(context, options, i18nFallbackLocale)
This shouldn't be needed since `loadLanguageAsync` handles merging right?

2021-10-17 19:49 UTC, rchl commented on src/templates/plugin.utils.js
> +export function mergeAdditionalMessages (context, { additionalMessages, localeCodes }, onlyLocales = null) {
I would suggest just passing what you need.
- just `i18n` instead of `context`
- just the needed options instead of all options

2021-10-17 19:52 UTC, rchl commented on src/templates/plugin.main.js
> +    i18n.additionalMessages = options.additionalMessages
I don't think that we should be exposing this on the Vue instance.
Should also update the types - move from `BaseOptions` to `Options`.

2021-10-19 14:50 UTC, existe-deja commented on src/templates/plugin.main.js
> +    i18n.additionalMessages = options.additionalMessages
fixed by removing it.

2021-10-19 14:51 UTC, existe-deja commented on src/templates/plugin.main.js
> +            mergeAdditionalMessages(context, options, i18nFallbackLocale)
fixed

2021-10-19 15:04 UTC, existe-deja commented on test/fixture/extend-locales/modules/externalModule/index.js
> +export default function () {
fixed

2021-10-19 15:04 UTC, existe-deja commented on test/fixture/extend-locales/pages/index.vue
> +    <div id="debug">{{ $i18n.messages }}</div>
fixed

2021-10-19 15:04 UTC, existe-deja commented on src/templates/plugin.utils.js
> +  })
fixed

2021-10-19 15:04 UTC, existe-deja commented on test/fixture/extend-locales/modules/externalModule/index.js
> +import lang from './lang'
fixed

2021-10-19 15:05 UTC, existe-deja commented on types/index.d.ts
> +  additionalMessages?: Array<LocaleMessages>
fixed by removing it

2021-10-19 15:05 UTC, existe-deja commented on test/module.test.js
> +describe.only('Extend Locale with additionalMessages', () => {
fixed

2021-10-19 15:06 UTC, existe-deja commented
I added docs and an extra test to ensure translations are always overridable.

2021-10-19 15:08 UTC, existe-deja commented on src/templates/plugin.utils.js
> +export function mergeAdditionalMessages (context, { additionalMessages, localeCodes }, onlyLocales = null) {
I followed the way loadLanguageAsync passes arguments. Do you want me to avoid destructuring?

2021-10-19 18:46 UTC, rchl requested changes

2021-10-19 18:46 UTC, rchl commented on test/fixture/extend-locales/lang/fr.js
> +export default {
This file can be removed now.

2021-10-19 18:46 UTC, rchl commented on test/fixture/extend-locales/lang/en.js
> +export default {
This file can be removed now.

2021-10-19 18:46 UTC, rchl commented on test/fixture/extend-locales/nuxt.config.js
> +module.exports = config
```suggestion
export default config
```

2021-10-19 18:46 UTC, rchl commented on types/internal.d.ts
> +  normalizedLocales: readonly LocaleObject[],
```suggestion
  normalizedLocales: readonly LocaleObject[]
```

2021-10-19 18:46 UTC, rchl commented on types/internal.d.ts
> +  additionalMessages?: Array<LocaleMessages>
I think it would make sense to have this property default to `[]` since it would simplify types and null checking

Also, for consistency, please use the `[]` syntax.

```suggestion
  additionalMessages: LocaleMessages[]
```

2021-10-19 18:46 UTC, rchl commented on src/core/hooks.js
> +  }
Can this just be:

```suggestion
  options.additionalMessages = []
  await this.nuxt.callHook('i18n:extend-locales', options.additionalMessages)
```

?

Can `buildHook` run more than once? Only then it would make some sense but then that would likely result in duplicate translations so we would want to avoid that anyway.

2021-10-19 18:46 UTC, rchl commented on src/templates/plugin.utils.js
> + * @param {Array<string> | string | null} onlyLocales?
Would prefer more specific parameters. For example:

```suggestion
 * @param {import('../../types').NuxtI18nInstance} i18n
 * @param {ResolvedOptions['additionalMessages']>} additionalMessages
 * @param {ResolvedOptions['localeCodes']>}  localeCodes
 * @param {string[] | null} [onlyLocales=null]
```

Note that I've changed `onlyLocales` to `string[]` since you could at call site ensure that it's an array.

2021-10-19 18:46 UTC, rchl commented on src/templates/plugin.utils.js
> +  }
This won't be needed if we ensure that it's always an array.

2021-10-19 18:46 UTC, rchl commented on src/templates/plugin.utils.js
> +  const locales = onlyLocales ? (Array.isArray(onlyLocales) ? onlyLocales : [onlyLocales]) : localeCodes
The caller can ensure that an array is passed to make this simper.

2021-10-19 18:52 UTC, rchl requested changes

2021-10-19 18:52 UTC, rchl commented on docs/content/en/extend-locales.md
> +Exemple:
(I'm splitting this suggestion into multiple comments since otherwise it breaks due to triple backticks)

The terminology is a bit random since we sometimes say messages and sometimes translations. Here are some suggestions.

```suggestion
---
title: Extending messages hook
description: "Nuxt hook to extend app's messages"
position: 14
category: Guide
---

If you're a **module author** and want that module to provide extra messages for your project, you can merge them into the normally loaded messages by using the `i18n:extend-messages` hook.

To do this, in your module's setup file listen to the Nuxt hook and push your messages. `@nuxtjs/i18n` will do the rest.

This is particularly useful if your module use translated content and you want to offer to users nice default translations.

Example:
```

2021-10-19 18:52 UTC, rchl commented on docs/content/en/extend-locales.md
> +  nuxt.hook('i18n:extend-locales', function (additionalMessages) {
I've realized that we are not extending locales here but messages.

```suggestion
  nuxt.hook('i18n:extend-messages', function (additionalMessages) {
```

2021-10-19 18:52 UTC, rchl commented on docs/content/en/extend-locales.md
> +</alert>
The terminology is a bit random since we sometimes say messages and sometimes translations. Here are some suggestions.

```suggestion
Now the project has access to new messages and can use them through `$t('my-module-exemple.hello')`.

<alert>
Because module's messages are merged with the project's ones, it's safer to prefix them.

Main project messages **will always override** the module's ones.
</alert>
```

2021-10-25 11:00 UTC, existe-deja commented on test/fixture/extend-locales/lang/fr.js
> +export default {
It's still required for the test with langDir option

2021-10-25 11:00 UTC, existe-deja commented on test/fixture/extend-locales/lang/en.js
> +export default {
It's still required for the test with langDir option

2021-10-25 11:00 UTC, existe-deja commented on test/fixture/extend-locales/nuxt.config.js
> +module.exports = config
not sure on this one

2021-10-25 11:01 UTC, existe-deja commented on types/internal.d.ts
> +  normalizedLocales: readonly LocaleObject[],
fixed

2021-10-25 11:04 UTC, existe-deja commented on src/core/hooks.js
> +  }
If you override additionalMessages like this, you loose de data you may have entered in nuxt.config.js. I fixed my code with the main idea of mutation options instead of keeping it "pure".

2021-10-25 11:05 UTC, existe-deja commented on src/templates/plugin.utils.js
> + * @param {Array<string> | string | null} onlyLocales?
fixed

2021-10-25 11:05 UTC, existe-deja commented on src/templates/plugin.utils.js
> +  }
fixed

2021-10-25 11:05 UTC, existe-deja commented on docs/content/en/extend-locales.md
> +Exemple:
fixed

2021-10-25 11:05 UTC, existe-deja commented on docs/content/en/extend-locales.md
> +  nuxt.hook('i18n:extend-locales', function (additionalMessages) {
fixxed

2021-10-25 11:05 UTC, existe-deja commented on docs/content/en/extend-locales.md
> +</alert>
fixed

2021-10-25 11:16 UTC, rchl commented on src/core/hooks.js
> +  }
You loose which data? I thought we agreed that `additionalMessages` is not supposed to be settable from nuxt.config.

2021-10-25 19:57 UTC, rchl commented on test/fixture/extend-locales/nuxt.config.js
> +module.exports = config
Why not? Mixing CommonJS and ES imports syntax is not ideal and Nuxt team recommends ES imports syntax.

Unless this has problems with testing framework which I guess it might if other fixtures do the same.

2021-11-02 11:52 UTC, existe-deja commented on src/core/hooks.js
> +  }
fixed with an extra test as additionalMessages could have been set by another module

2021-11-02 12:57 UTC, rchl commented on src/core/hooks.js
> +  }
How so?

The code looks like this right now:

```js
  if (!options.additionalMessages) {
    options.additionalMessages = []
  }
  await this.nuxt.callHook('i18n:extend-messages', options.additionalMessages)
```

and I really can't see how `options.additionalMessages` can be anything else than undefined at the point of the `if` check.

2021-11-02 13:04 UTC, existe-deja commented on src/core/hooks.js
> +  }
If module A use i18n:extend-messages hook and module B either, at some point additionalMessages have something

2021-11-02 13:38 UTC, rchl commented on src/core/hooks.js
> +  }
I'm talking about

```js
  if (!options.additionalMessages) {
    options.additionalMessages = []
  }
```

This code should execute only once within the i18n module itself.

2021-11-03 13:10 UTC, existe-deja commented on src/core/hooks.js
> +  }
You are totally right, I mixed test names so it was called twice. Fixed now.

2021-11-04 07:55 UTC, merged

2021-11-04 07:55 UTC, rchl commented
Thanks!