Fixed matching browser locale when the only matching component is the language
nuxt-modules/i18n pull request #855
Opened 2020-08-20 11:17 UTC by koendeschacht

Previously, nuxt-i18n would not find a match with app locales `['en-IN', 'hi-IN']` and browser locales: `['en-US', 'en-GB', 'en']`. Now the following cases:

app locales: ['en-IN', 'hi-IN'] browser locales: `['en-US', 'en-GB', 'en']`

and

app locales: ['en-IN', 'hi-IN'] browser locales: `['en-US', 'en-GB']`

result in the chosen locale `en-IN`.

2020-08-23 18:32 UTC, rchl requested changes
Ops. Looks like I forgot to send this feedback. Sorry for the delay.

2020-08-23 18:32 UTC, rchl commented on src/templates/utils-common.js
> +        }
This is shorter:
```suggestion
        const languageCodeLocale = appCode.split('-')[0].toLowerCase()
```

but I'm not sure I agree with the logic where

> app locales: ['en-IN', 'hi-IN'] browser locales: `['en-US', 'en-GB']` result in the chosen locale `en-IN`.

I'm not sure if those en-* variants are sufficiently similar to use them as a substitute. I mean, we know that English US and UK are very similar and would work but I'm not sure if that applies in all cases (for other countries).

2020-08-24 08:10 UTC, koendeschacht commented on src/templates/utils-common.js
> +        }
Good point. I'm not sure either. As I was modifying the PR, also started to doubt some other cases. Take for example:
nuxt-i18n config: 
```
{
locales:['en-CA', 'fr-CA'],
defaultLocale: 'en-CA'
}
```

and browser locales 
```
['en-UK', 'fr']
```

Which one should be matched here? Or

config: 
```
{
locales:['fr-CA', 'en-CA'],
defaultLocale: 'fr-CA'
}
```

and browser locales 
```
['fr', 'en-CA']
```

?? 

I was thinking however, the problem of matching browser locales has existed for such a long time, there should be specification of reference implementation out there somewhere. I'll already found these:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat/supportedLocalesOf
https://tc39.es/ecma402/#sec-supportedlocales 

The default matcher in Javascript seems to be 'best-fit', but if my quick googling is correct neither Firefox or the V8 engine actually implemented this:

https://searchfox.org/mozilla-central/source/js/src/builtin/intl/CommonFunctions.js#575
https://chromium.googlesource.com/v8/v8/+/4.3.49/src/i18n.js?autodive=0%2F%2F (search for bestFitSupportedLocalesOf)

The fallback match algorithm is 'lookup' but I could not quickly grasp the specification and apply it to this case. I'll continue on it later tonight, and maybe also see  whether there are some server packages (Spring? Rails?) that have an implementation of the 'best-fit' algo.

2020-11-28 21:04 UTC, rchl commented on src/templates/utils-common.js
> +        }
It seems that #965 is pretty much having the same effect but also adds support for matching ISO codes so I'll handle this issue through that other PR.

Thanks for your efforts though and sorry that it took forever.

2020-11-28 21:05 UTC, closed without merging